=== SmirnovAlexander/DBMS/XMLHandling/departments_data.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT faculty_info (students,departments)>
<!ELEMENT students (student)*>
<!ELEMENT student (surname,marks)>
<!ELEMENT marks (mark)*>
<!ELEMENT mark (subject,grade)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT departments (department)*>
<!ELEMENT department (name,head,subjects)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT head (#PCDATA)>
<!ELEMENT subjects (subject)*>

=== SmirnovAlexander/DBMS/XMLHandling/departments_data.xml
<?xml version="1.0" encoding="utf-8"?> 
<!-- <!DOCTYPE faculty_info SYSTEM "departments_data.dtd"> -->
<faculty_info>
    <students>
        <student>
            <surname>Иванов</surname>
            <marks>
                <mark>
                    <subject>Математический анализ</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Алгебра</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Геометрия и топология</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Математическая физика</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Анализ данных</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Алгоритмы СУБД</subject>
                    <grade>4</grade>
                </mark>
            </marks>
        </student>
        <student>
            <surname>Смирнов</surname>
            <marks>
                <mark>
                    <subject>Математический анализ</subject>
                    <grade>3</grade>
                </mark>
                <mark>
                    <subject>Алгебра</subject>
                    <grade>3</grade>
                </mark>
                <mark>
                    <subject>Геометрия и топология</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Математическая физика</subject>
                    <grade>3</grade>
                </mark>
                <mark>
                    <subject>Анализ данных</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Алгоритмы СУБД</subject>
                    <grade>4</grade>
                </mark>
            </marks>
        </student>
        <student>
            <surname>Филиппов</surname>
            <marks>
                <mark>
                    <subject>Математический анализ</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Алгебра</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Геометрия и топология</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Математическая физика</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Анализ данных</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Алгоритмы СУБД</subject>
                    <grade>4</grade>
                </mark>
            </marks>
        </student>
        <student>
            <surname>Явич</surname>
            <marks>
                <mark>
                    <subject>Математический анализ</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Алгебра</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Геометрия и топология</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Математическая физика</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Анализ данных</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Алгоритмы СУБД</subject>
                    <grade>4</grade>
                </mark>
            </marks>
        </student>
        <student>
            <surname>Жилкин</surname>
            <marks>
                <mark>
                    <subject>Математический анализ</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Алгебра</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Геометрия и топология</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Математическая физика</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Анализ данных</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Алгоритмы СУБД</subject>
                    <grade>5</grade>
                </mark>
            </marks>
        </student>
        <student>
            <surname>Литвинов</surname>
            <marks>
                <mark>
                    <subject>Математический анализ</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Алгебра</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Геометрия и топология</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Математическая физика</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Функциональное программирование</subject>
                    <grade>5</grade>
                </mark>
            </marks>
        </student>
        <student>
            <surname>Бондаренко</surname>
            <marks>
                <mark>
                    <subject>Математический анализ</subject>
                    <grade>3</grade>
                </mark>
                <mark>
                    <subject>Алгебра</subject>
                    <grade>3</grade>
                </mark>
                <mark>
                    <subject>Геометрия и топология</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Математическая физика</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Функциональное программирование</subject>
                    <grade>3</grade>
                </mark>
            </marks>
        </student>
        <student>
            <surname>Пенская</surname>
            <marks>
                <mark>
                    <subject>Математический анализ</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Алгебра</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Геометрия и топология</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Математическая физика</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Функциональное программирование</subject>
                    <grade>5</grade>
                </mark>
            </marks>
        </student>
        <student>
            <surname>Ивлев</surname>
            <marks>
                <mark>
                    <subject>Математический анализ</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Алгебра</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Геометрия и топология</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Математическая физика</subject>
                    <grade>4</grade>
                </mark>
                <mark>
                    <subject>Функциональное программирование</subject>
                    <grade>4</grade>
                </mark>
            </marks>
        </student>
        <student>
            <surname>Лодыгин</surname>
            <marks>
                <mark>
                    <subject>Математический анализ</subject>
                    <grade>3</grade>
                </mark>
                <mark>
                    <subject>Алгебра</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Геометрия и топология</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Математическая физика</subject>
                    <grade>5</grade>
                </mark>
                <mark>
                    <subject>Функциональное программирование</subject>
                    <grade>5</grade>
                </mark>
            </marks>
        </student>
    </students>
    <departments>
        <department>
            <name>Кафедра информационно-аналитических систем</name>
            <head>Михайлова Елена Георгиевна</head>
            <subjects>
                <subject>Математический анализ</subject>
                <subject>Алгебра</subject>
                <subject>Геометрия и топология</subject>
                <subject>Математическая физика</subject>
                <subject>Анализ данных</subject>
                <subject>Алгоритмы СУБД</subject>
            </subjects>
        </department>
        <department>
